import Head from "next/head"
import Image from "next/image"
import styles from "../styles/Home.module.css"
import Footer from "../components/Footer"
import Formation from "../components/Formation"

import Header from "../components/Header"

export default function Home() {
  return (
    <div className="text-white h-screen snap-y snap-mandatory overflow-scroll z-0">
      <Head>
        <title>Isake Neut</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
        \
      </Head>
      <main>
        <Header />
        <Formation />
        <Footer />
      </main>
    </div>
  )
}
