import Head from "next/head"
import Image from "next/image"
import styles from "../styles/Home.module.css"
import Savoir from "../components/Savoir"
import Experience from "../components/Experience"
import Formation from "../components/Formation"
import Project from "../components/Project"
import ContactMe from "../components/ContactMe"
import { Experiences, Formations, Personal, Projects, Social } from "../typings"
import { Parallax, ParallaxLayer } from "@react-spring/parallax"
import Header from "../components/Header"
import Parallaxs from "../components/Parallaxs"
import ExperienceCard from "../components/ExperienceCard"
// import { fetchExperiences } from "../utils/fetchExperiences"
// import { fetchProjects } from "../utils/fetchProjects"
// import { fetchSkills } from "../utils/fetchSkills"
// import { fetchFormations } from "../utils/fetchFormation"
// import { fetchSocial } from "../utils/fetchSocial"
// type Props = {
//   personal: Personal[]
//   experiences: Experience[]
//   formations: Formation[]
//   projects: Project[]
//   social: Social[]
// }

export default function Home() {
  return (
    <div className="text-white h-screen snap-y snap-mandatory overflow-scroll z-0">
      <Head>
        <title>Isake Neut</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />\
      </Head>
      <main>
        <Header />
        {/* <Experience />
        <Parallaxs /> */}
        <Formation />
      </main>
    </div>
  )
}
